# Generated by Django 3.2.8 on 2021-12-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211204_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='users/user_icon.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
