# Generated by Django 3.2.8 on 2021-12-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='users/user_icon.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
