version: "3"
services:
  educa:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 80
    container_name: educa
    volumes:
      - static_volume:/home/app/educa/staticfiles
      - media_volume:/home/app/educa/mediafiles
    command: gunicorn educa.wsgi:application -b 0.0.0.0:80 --workers=3
    env_file:
      - ./.env.prod
    depends_on:
      - db
  dpchannel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 80
    container_name: dpchannel
    env_file:
      - ./.env.prod
    command: daphne -b 0.0.0.0 -p 80 educa.asgi:application
    depends_on:
      - educa

  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/educa/staticfiles
      - media_volume:/home/app/educa/mediafiles
    ports:
      - "80:80"
    depends_on:
      - educa

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
