version: "3"
services:
  educa:
    build: .
    ports:
      - "8000:8000"
    container_name: educa
    volumes:
      - ./:/educa/
    env_file:
      - ./.env.dev
    volumes:
      - static_volume:/home/app/educa/staticfiles
      - media_volume:/home/app/educa/mediafiles
    command: python manage.py runserver 0.0.0.0:8000
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  static_volume:
  media_volume:
  redisdata:
