# Generated by Django 3.2.8 on 2021-12-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
