# Generated by Django 3.2.8 on 2021-12-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attempts',
            field=models.ManyToManyField(through='assignments.Attempt', to='courses.Enrollment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptchoice',
            unique_together={('choice', 'attempt')},
        ),
    ]
